### ISSUE TITLE
add once()

### ISSUE THREAD

**Issue by chrislrobert** [getodk/xforms-spec#10]
ODK and SurveyCTO both support a once() function now, most often used with random() like so:

once(random())

The idea is that only one value is generated per form instance; once the form has a value, it maintains that value rather than replacing it. once() takes one parameter (a function call or expression).

Without this function, for example, random() was inappropriate for randomizing survey elements because the random draw would be re-calculated periodically (and, certainly, when saving and then editing). once() is also helpful when, e.g., capturing the date and time when a part of the survey is first reached. There may be other potential uses as well.

**Comment by MartijnR** [comment]
Thanks, forgot that one! (also supported in Enketo)
