### ISSUE TITLE
Configure auto-send and auto-delete at the form level

### ISSUE THREAD

**Issue by yanokwa** [getodk/xforms-spec#100]
**Problem**
We have a user whose campaign has forms that need to be deleted on send because they are sensitive. The same user has other forms that need to be kept on the device because the data is useful to the day to day work of the enumerator.

**Proposal**
In the settings sheet of the XLSForm, we will add an `auto_send` and `auto_delete` heading. If the values underneath this heading is true(), then the form will behave accordingly and override the settings of the device.

I'm not sure how we represent this in an XForm. My first pass is that we use the [submission element](https://www.w3.org/TR/xforms/#submit) and add a namespaced attribute. @MartijnR @mitchellsundt @chrisroberts @meletis Any feedback on this approach?

**Comment by MartijnR** [comment]
I think adding these to the submission element is great. In fact, I think we already agreed on an auto-send attribute: https://github.com/opendatakit/xforms-spec/issues/44

For the reasons mentioned in the other discussion, I think this should be a boolean value. So this issue could add:

```xml
<submission orx:auto-delete="true">
```

**Comment by yanokwa** [comment]
Great to see Yaw of the past thought this was a good idea. Consistency is important 😂!

What do you think, @lognaturel?

**Comment by lognaturel** [comment]
@yanokwa should search the open issues before filing new ones! 😁

Yes, I think we should go ahead and incorporate what was agreed on in #44 now and the addition proposed by @MartijnR for `auto-delete` sounds great to me.

**Comment by yanokwa** [comment]
And for completeness, the implementation in Collect is at https://github.com/opendatakit/collect/issues/791

**Comment by lognaturel** [comment]
I want to be 100% sure I understand how these settings are used. As I understand it, the intent is that they always override whatever the client setting are. So if the client has auto send off or set to wifi only or whatever, adding `auto-send="true"` at the form level will mean it's always auto sent. Did I get that right?

**Comment by yanokwa** [comment]
Yes, regardless of what the client's settings say, it should send via WiFi or Cell.

**Comment by lognaturel** [comment]
How does this interact with the conversation at #133? In other words, should `method` be required when the only submission attributes are `orx:auto-delete` and/or `orx:auto-send`? Is `method` only required when there's also a value for `base64RsaPublicKey`?

**Comment by MartijnR** [comment]
I too have these questions about whether and when `method` is, or officially should be, required.

**Comment by lognaturel** [comment]
As far as I know, `method` is not used for anything beyond verifying that its value matches the expected one. 

I'd be fine with saying that `method` is optional and defaults to `post`. This would be different from W3C XForms. Again, would be good to get some sanity checks, @yanokwa, @ggalmazor, @ukanga.

**Comment by yanokwa** [comment]
I'm probably missing something, but it seems like we don't have to deviate from XForms here. Why not require `method:post` but allow `method:post-form-data` for backwards compatibility?

**Comment by lognaturel** [comment]
The question is if we're only setting specialized ODK attributes (e.g. auto-send/auto-delete) and not the `action`, should `method` need to be specified. I think a friendly approach is to never require it and always default to `post` since I don't think anything in the ecosystem supports any other methods.

**Comment by yanokwa** [comment]
My assumption here is that these forms aren't being generated by humans anymore. It's trivial for the form design tool to just put "method:post" so I say we do it and don't deviate.

**Comment by lognaturel** [comment]
Fair enough. It just feels really odd to have `<submission orx:auto-delete="true" method="post">` when an action isn't also specified. And we don't want to require having an action specified there because some people will prefer setting the server at the client level rather than at the form level.

**Comment by yanokwa** [comment]
Ah, I see! If there is no `action`, then a `method` doesn't make sense. I think it's OK to drop `method` then.

**Comment by MartijnR** [comment]
Thanks @yanokwa and @lognaturel. You are using these attributes already with the openrosa namespace, right? If so that will the namespace to document.

**Comment by MartijnR** [comment]
never mind. I see the answer in the pyxform issue.
