### ISSUE TITLE
Proposal: add-on section describing format for csv log

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#102]
In #94, we have described a way to request an audit log with instances. This log would initially include timing data and could be extended to include other kinds of metadata such as location. 

We have also discussed developing an add-on to describe a standard format for this log. @nap2000 has done a bunch of research and design work at opendatakit/collect#257. The proposed format for that file is a comma-separated CSV with the following header:

```
event, node, start, end
```
The event column would have a fixed set of possible values described [here](https://docs.google.com/document/d/1LqVlVpePjA7Q1snjhA_ZQoDuzFqbtQcIygwcEzO_LJs/edit#)

The node column would be populated with the question node path for events that refer to a specific node.

The start and end columns would be timestamps for the event beginning and end.

**Comment by MartijnR** [comment]
Would be great to add this. A separate page might good for this. No comments from my side on the format.

**Comment by lognaturel** [comment]
Awesome, I'll try to get a PR soon.

**Comment by lognaturel** [comment]
At long last, closed by #234.
