### ISSUE TITLE
Hashing/digest support

### ISSUE THREAD

**Issue by smoyte** [getodk/xforms-spec#103]
A client wants to be able to compute e.g. an SHA digest over some concatenated answers in a form to produce a secure unique ID.

Could we add something like this: 

https://www.w3.org/MarkUp/Forms/wiki/XPath_Expressions_Module#The_digest.28.29_Function

It doesn't have to be that fancy though.

I'm not sure how you'd want to namespace and I don't really get what the `xf` namespace is or if any of that is supported currently. I leave that up to y'all to suggest.

Thanks!

**Comment by lognaturel** [comment]
Oh my goodness, could the state of the W3C XForms spec possibly be more confusing?! So it looks like what you've linked to is the working draft for XForms 2.0? I think `xf` is the prefix used for `http://www.w3.org/2002/xforms`.

But luckily, it looks like `digest` is described in the XForms 1 official spec [here](https://www.w3.org/TR/xforms/#fn-digest) and that it hasn't changed. So I'd be in favor of adding that as-is.

**Comment by MartijnR** [comment]
> So I'd be in favor of adding that as-is.

+1

**Comment by smoyte** [comment]
Sounds good to me but I admit:

![image](https://cloud.githubusercontent.com/assets/702320/24570496/a376a3dc-1639-11e7-8860-d5fd41851f25.png)

**Comment by lognaturel** [comment]
Our first non-human contributor! 😆

Adding it to the specification is the fun part. I believe you can submit a pull request that adds the function to the XPath functions table and has something like "As in XForms 1.0" in the description with a link to https://www.w3.org/TR/xforms/#fn-digest. @MartijnR does that sound right?

But of course, then it needs to be added to the implementations. For Collect, you'd file an issue in the javarosa repo. If you can also submit a pull request, great! But folks there can also help with the implementation. I think that for Enketo, you'd file the issue [here](https://github.com/enketo/enketo-core).

**Comment by MartijnR** [comment]
I see this has/is moving forward in Collect. I'll create a PR so we can close this.
