### ISSUE TITLE
Add support for contains(), starts-with(), ends-with() functions

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#105]
starts-with() and contains() as in XPath 1.0. ends-with() is XPath 2.0 (I believe)

This will provide powerful search capabilities for secondary instances (including external). Especially after #88, it would greatly increase the search capabilities.

E.g. finding items that do not contain a certain string (as requested [here](https://groups.google.com/forum/#!topic/opendatakit/lMams3XcaNc)) with `not(contains(..))`

Currently, we can only really search XML instances for exact value matches.

**Comment by lognaturel** [comment]
Seems good to me. I propose that when adding functions that aren't in XPath 1.0, we use the XPath 3.0 docs even if the function was introduced in XPath 2.0. From what I've seen, the definitions for the two are generally the same or very similar. But having some consistent rule to follow would make things a little easier to reason about, I think.

**Comment by MartijnR** [comment]
Yes, sounds good!

**Comment by dcbriccetti** [comment]
I’m starting on this, at Hélèn’s suggestion.

**Comment by dcbriccetti** [comment]
How do these tests look?
```
testEval("contains('a', 'a')",      true);
testEval("contains('a', 'b')",      false);
testEval("contains('abc', 'b')",    true);
testEval("contains('abc', 'bcd')",  false);
testEval("not(contains('a', 'b'))", true);
testEval("starts-with('abc', 'a')", true);
testEval("starts-with('', 'a')",    false);
testEval("starts-with('', '')",     true);
testEval("ends-with('abc', 'a')",   false);
testEval("ends-with('abc', 'c')",   true);
testEval("ends-with('', '')",       true);
```

**Comment by MartijnR** [comment]
nice! Here are some more (though may not add anything):

contains: https://github.com/enketo/enketo-xpathjs/blob/master/test/spec/string-functions-native.spec.js#L152-L183
starts-with: https://github.com/enketo/enketo-xpathjs/blob/master/test/spec/string-functions-native.spec.js#L119-L150

**Comment by dcbriccetti** [comment]
Hi @MartijnR. Thanks for the glimpse of your nifty Enketo. I hear good things about it (and you).

**Comment by MartijnR** [comment]
Thank you and thanks for adding these functions! :)
