### ISSUE TITLE
Add W3C XForms range control

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#109]
Add support for the `range` control as described [here](https://www.w3.org/TR/xforms/#ui-range). Initially we could omit the `incremental` property since I don't believe any tools in the ODK XForms ecosystem supports events currently.

XLSForm/pyxform#79 takes this up from the XLSForm angle but we probably don't need to think too much about that until JavaRosa implements it.

@spatialdude

**Comment by MartijnR** [comment]
I'm all for it. 🎉

**Comment by lognaturel** [comment]
Bit of a procedure question -- since this is straight from the W3C standard, I don't think it needs much discussion. Are we ready to add it to the spec or does it make more sense to wait until something in the ecosystem actually implements it? If we do add it now, I do think it would be nice to have some way to mark it as "pending implementation."

**Comment by MartijnR** [comment]
I think we can add it to the spec now, without any message. It will become a mess to do, and maintain, this for all clients.  

Best to do this ourselves individually in my opinion as e.g. https://developer.microsoft.com/en-us/microsoft-edge/platform/status/. We could perhaps add links to Enketo/ODK/Survey123 implementation status overviews.

**Comment by lognaturel** [comment]
Sounds great to me!
