### ISSUE TITLE
Proposal: add spinner appearance on range control

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#111]
For our new `range` control (#109), how about adding an `appearance` value of something like `spinner` or `picker` to get something that looks like the following in Android (opendatakit/collect#105):
<img src="https://i.stack.imgur.com/XfdH6.png" width="200">

I think there are several equivalent HTML interfaces that would look nice and be useful.

**Comment by MartijnR** [comment]
Yes, let's agree on some.

I like "slider" and "spinner". Are you referring to a slider with "picker", perhaps?

Enketo has a rogue undocumented custom client feature for a slider range control "analog-scale" that (re-)uses these appearances. Maybe some of these could be useful:

for slider: "horizontal" (default is vertical), "no-ticks" (default has ticks)  (and "analog-scale" but probably not)

and also perhaps:

"distress" (though this one is quite specific)

<img width="635" alt="screen shot 2017-05-03 at 4 48 23 pm" src="https://cloud.githubusercontent.com/assets/627350/25684805/a610f402-3020-11e7-85b9-d44d2803ed4b.png">
<img width="168" alt="screen shot 2017-05-03 at 4 48 15 pm" src="https://cloud.githubusercontent.com/assets/627350/25684806/a610cd4c-3020-11e7-9dd7-2cf0d205ea1d.png">
<img width="162" alt="screen shot 2017-05-03 at 4 48 01 pm" src="https://cloud.githubusercontent.com/assets/627350/25684807/a6149558-3020-11e7-9710-5737715919ad.png">
<img width="115" alt="screen shot 2017-05-03 at 4 51 30 pm" src="https://cloud.githubusercontent.com/assets/627350/25684839/d25b15ba-3020-11e7-8793-8f7930231c96.png">

**Comment by lognaturel** [comment]
I figured a horizontal slider with ticks at every step (your first screenshot) would be the default since it's what the W3C spec seems to default to. 

I like `vertical` and `no-ticks`. Or should that be `vertical`, `vertical-no-ticks` and `horizontal-no-ticks`?

To me, spinner or picker would be alternative names for the thing I had in my screenshot. I think that's what the W3C spec refers to as a "rotary control." On the web, that might be something like
<img src="http://www.jqueryscript.net/images/Simple-jQuery-Number-Picker-Spinner-Plugin-dpNumberPicker.jpg" width="150">
I got that screenshot from a jquery plugin site and they call it a picker/spinner plugin! I don't really have a preference though `picker` feels a bit more generic to me which I like.

`distress` I don't think we would add to Collect. I think at the moment Enketo has it as an integer appearance. Would you change that?

How are you specifying the start and end labels in the form?

**Comment by lognaturel** [comment]
Oh, I just noticed you suggested that the vertical version be the default. Any particular reason for that? I would have thought horizontal because it's usually the default implementation for the underlying slider controllers and more common in interfaces.

**Comment by MartijnR** [comment]
Fine with me to make `horizontal` the default. No-ticks is an additional appearance so `vertical no-ticks` and `horizontal no-ticks`. The advantage of that approach is that we can re-use and keep the vocabulary small (e.g. horizontal can also be used for select and select1 widgets).

Shall the `slider` be the default as well? (so `slider horizontal` would basically be ignored).

I think I'll convert `distress` to a range widget (with backwards compatibility). Right now it has a hardcoded min, max and step.

The min-max labels are very much a hack with a `|` separator which I think is not suitable for the spec. We briefly discussed this approach [here](https://groups.google.com/forum/#!searchin/opendatakit-developers/analog$20scale%7Csort:relevance/opendatakit-developers/FbMQ3usvrWY/iiuscSSEDQAJ). It might be worth discussing how to add min/max text properly in the future as it's probably a worthwhile generic feature.

**Comment by lognaturel** [comment]
Sounds good about appearances being combinable. I don't think Collect allows that anywhere else but since appearances are implemented in an add-hoc manner anyway it shouldn't be a problem. And I believe that pyxform just puts whatever is in the column in the XForm it generates, right?

Defaults get a little confusing to me in a world where appearances combine. I suppose no appearance, `slider horizontal`, `slider horizontal ticks` and `slider` would all be equivalent to  `slider horizontal ticks`, really. Is `slider` necessary or can `horizontal` and `vertical` imply horizontal slider and vertical slider? Same question about `ticks`, I suppose only `no-ticks` is needed? And in fact, maybe `horizontal` isn't required? 

But maybe all of these optimizations are just confusing and it makes sense to document a superset (`horizontal`, `vertical`, `ticks`, `no-ticks`, `slider`, `picker`). Then to codify how they can/can't combine and what the defaults are, the logic can be something like:
```
if appearances contains picker:
    show picker
else:
    if appearances contains vertical:
        vertical slider
    else:
        horizontal slider

    if appearances contains  no-ticks:
        slider with no ticks
    else:
        slider with ticks
```

Sounds good about `distress`.

Interesting conversation about the min/max text. Makes sense to discuss separately.

**Comment by lognaturel** [comment]
Or maybe an easier way to document things is not to mention the individual appearances and how they combine but just have something like:

| Desired look   | Appearance |
| ------------- | ------------- |
| Horizontal slider with ticks | none  |
| Horizontal slider without ticks | `no-ticks`  |
| Vertical slider with ticks            | `vertical` |
| Vertical slider without ticks       | `vertical no-ticks` |
| Picker                                          | `picker` |

Not clear to me whether clients should then do the kind of logic I was describing above or strictly implement these combinations.

**Comment by MartijnR** [comment]
Yes, this looks good. I would just change the second line to just `no-ticks`.

**Comment by lognaturel** [comment]
Cool, makes sense. I changed it in the table to keep it up to date.

And how do you feel about hardcoding those combinations vs. allowing other ways of encoding the same "look and feel"?

**Comment by MartijnR** [comment]
Sorry, I don't quite understand your question. Are you referring to how it's exposed in XLSForm to users?

**Comment by lognaturel** [comment]
I mean more in terms of what clients actually accept. There's a choice between sticking strictly to the table or allowing things like `horizontal no-ticks` (same meaning as `no-ticks`). The former is somewhat simpler but means the individual appearances don't have independent meaning. The latter is weird because there are undocumented combinations. But it's probably more practical in the sense that there are sensible fallbacks (see the pseudocode I was suggesting above). I may be making this unnecessarily complicated, though!

**Comment by MartijnR** [comment]
Oh I see. I think the clients should accept everything and could simply ignore appearance items (from the space-separated appearance list) that it doesn't support or that are defaults, e.g. using your pseudo-code. So if we document only the table and a user still adds 'horizontal', the widget should ignore this item (by not looking for it).

**Comment by lognaturel** [comment]
Awesome! 

I'm exploring the spec/reality fault line. 😜

**Comment by issa-tseng** [comment]
So.. if someone enters `no-ticks vertical` what's the behaviour? It's a true space-separated orderless list yes?

**Comment by lognaturel** [comment]
@clint-tseng Yes, `no-ticks vertical` and `vertical no-ticks` should result in the same vertical slider with no ticks. Also `pizza no-ticks vertical horizontal vertical vertical`.

**Comment by MartijnR** [comment]
`vertical` will be documented here: https://github.com/XLSForm/xlsform.github.io/issues/129
`picker` is part of https://github.com/XLSForm/xlsform.github.io/pull/122

I think `no-ticks` was not implemented in Collect. It also hasn't been in Enketo (the above screenshot are for some custom widget). Shall we close this and document/implement `no-ticks` once there is a demand for it?

**Comment by lognaturel** [comment]
`no-ticks` is in Collect! But yes, we can close this.
