### ISSUE TITLE
format-date() does not translate to the form's language

### ISSUE THREAD

**Issue by alxndrsn** [getodk/xforms-spec#122]
As implemented at https://github.com/opendatakit/javarosa/blob/690844454c29e76352f901c301d5d12d93facc75/src/org/javarosa/core/model/utils/DateUtils.java#L273-L291, `format-date()` always uses English when rendering `%a` and `%b` options.

These [options are defined](https://opendatakit.github.io/xforms-spec/#xpath-functions) as:
* `%a` short text day (_Sun_, _Mon_, etc)
* `%b` short text month (_Jan_, _Feb_, etc)

I hope these are only used for display purposes, in which case it would be better if they were translated into the display language of the form.

**Comment by lognaturel** [comment]
It seems like you have some kind of urgency around this. Additional context, use case, etc would really help! In particular, why is it time-sensitive?

I agree the usefulness of `%a` and `%b` is limited by the fact that they're not localized. Perhaps we can amend the specification and implementations to require localization but we should think carefully through the implications. @MartijnR?

**Comment by alxndrsn** [comment]
@lognaturel we require this for a non-English deployment which went live recently.

We can work around this indefinitely by writing our own custom function.

This function will likely be called `format-date-tr()`, and would call out to our standard translation library to get day and month names as desired.

Generally, I'm not keen on adding custom functions to xforms, but it certainly is convenient :¬)

**Comment by MartijnR** [comment]
Would be nice indeed. In this case, we may have to think about the implementation as of course we want to avoid having to add translations strings to our code. If we rely on native Date objects there are likely differences in how a day or month is abbreviated, capitalized and with how many characters (between the different programming languages or OS's?). 

Would we make the spec for `%a` and `%b` flexible to use whatever is natively available that is closest to 3 characters or something like that?

**Comment by MartijnR** [comment]
If implementing this in Enketo, I think I would choose to use the client's locale instead of the form language (and hope that in the future those can usually be in sync because of [this](https://github.com/XLSForm/xlsform.github.io/issues/73)). The spec could say 'Form language' though, I think.

**Comment by lognaturel** [comment]
That sounds good to me. How about something like
- `%a` short text day, localized (e.g. Sun, Mon... in English or Dim, Lun... in French - exact format will vary by implementation)
- `%b` short text month, localized (e.g. Jan, Feb... in English or Jan, Fev... in French - exact format will vary by implementation)

Caveat is that I'm not totally sure JavaRosa will be able to access the locale set by Collect. I think updating the spec is a good idea but Collect may deviate from it.

**Comment by lognaturel** [comment]
(Or I guess I should say on the Collect side there might be some trickery needed to pass the locale to JR and it may be a bit before it's implemented unless @alxndrsn you're planning to look into it.)

@MartijnR I hadn't even thought about using the form language. Yes, I think using the client language makes the most sense.

**Comment by alxndrsn** [comment]
I'll need to look at the code to clearly understand the distinction between client locale and form language, but for me the expected behaviour would be that the date summary would appear in the same language as the surrounding text in the form.

E.g. if:
* my OS locale is `en_GB`, and
* my browser is `es_ES`, and
* on my-enketo-app.example.com I select UI language of `fr`

I'd expect to see:
* enketo forms with French text
* dates from `format-date()` within that from with French text

**Comment by MartijnR** [comment]
I agree that would the way we should strive to do this (i.e. use form language, and the descriptions @lognaturel proposed). 

However, for pragmatic reasons, since there is no mechanism to pass a form locale to an XPath Evaluator (a compliant one), some of us may have to deviate from the spec and use the client locale instead (and hope that in the future client locale and form locale are synced anyway). 

I just thought of 2 other issues. 

1. If an XPath function returns a different value when the language changes, should it update all format-date() calculations in the form when the user switches to another language while traversing the form?

2. The language names in our XForms are human readable and not known IANA language codes (subtags) that a Date parser understands, unless [this technique](https://github.com/XLSForm/xlsform.github.io/issues/73) is used. I think we should advocate that technique anyway, but thought I should bring this up.

If others would prefer to let the spec say 'client locale' instead of 'form locale' for pragmatic reasons, that would be fine with me. We can then focus our efforts on loading a form with the client locale (browser for Enketo) as default form language (if it exists) and assume most will not need to switch form language after that.

**Comment by alxndrsn** [comment]
> However, for pragmatic reasons, since there is no mechanism to pass a form locale to an XPath Evaluator (a compliant one)

I wouldn't expect the locale to be passed as an argument to the XPath Evaluator, but I'd expect the XPath Evaluator to know the current locale of the form/client.

> 1. If an XPath function returns a different value when the language changes, should it update all format-date() calculations in the form when the user switches to another language while traversing the form?

Yes, I think so.  Recalculating all values doesn't seem like a big chore when you're already re-translating all the labels etc.  Do you expect users to change language frequently while filling a single form?

> 2. The language names in our XForms are human readable and not known IANA language codes (subtags) that a Date parser understands, unless this technique is used. I think we should advocate that technique anyway, but thought I should bring this up.

It sounds like I have a very different experience of the mechanics of form translation to you two, so I should check how Collect and Enketo both handle it.  That said, in reference to

> If others would prefer to let the spec say 'client locale' instead of 'form locale' for pragmatic reasons

I'm now not clear what the difference is.  Does a form itself have a locale?  Is what I described in https://github.com/opendatakit/xforms-spec/issues/122#issuecomment-302343741 "client locale"?

**Comment by lognaturel** [comment]
Yes, you got the idea right in your comment in #122. Clients support different languages by having translations for standard widgets, etc. Independently of that, form creators can define text for arbitrary languages in their form definitions. I was talking to someone today who wants slightly different text for different contexts her form is used in so she had the idea of having "Phone-administered" and "Self-administered" as two languages. Language identifiers are free-form and may or may not correspond to natural languages or languages supported by the clients.

On the JR side, it may be as simple as calling `Locale.getDefault()` to get the client locale but I'm not sure. For the form language... I suppose that we could try to parse the languages as though they had @MartijnR's proposed format.

How about adding a version that takes an explicit language parameter as in XPath 3.0 [here](https://www.w3.org/TR/xpath-functions-30/#func-format-date)? Looks like `format-date` was only introduced in 3.0 anyway so why not just have both?

**Comment by MartijnR** [comment]
If we want form designers to be able to explicitly provide the locale, a third parameter is good. But this wouldn't meet @alxndrsn requirement I think (unless we would also add another currentLanguage() function or something). If there is no demand for explicitly specifying this, we could leave that until there is a demand.

Interesting that XPath 3.0 has something similar (though we'll be deviating or in this case XPath is deviating from us). 

For our 2-parameter function, how about we describe the locale determination as:

_If form locale can be determined - by including a valid IANA subtag between brackets in the language name, e.g. "Français (fr)" - that locale will be used. If that cannot be determined the locale of the client will be used (e.g. the browser or app)._

**Comment by lognaturel** [comment]
Oh right, I'm sorry. The three-parameter function isn't so helpful for a multi-language form which is probably the whole point!

What you suggest works for me.
