### ISSUE TITLE
Allow <output> as child of text entries used as jr:constraintMsg?

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#125]
We've discovered in opendatakit/javarosa#36 that Collect does not support `output` as a child of a `text` used as a `jr:constraintMsg`. It looks like Enketo does support this. 

The spec states that `output` is a "child of a &lt;label&gt; or &lt;hint&gt; element" [here](https://opendatakit.github.io/xforms-spec/#body-elements). Should we expand this a bit? @MartijnR how would you describe where Enketo allows it? Is it always allowed in `text` entries, basically?

**Comment by MartijnR** [comment]
I don't think we can support this as jr:constraintMsg is not an XPath expression. It should not be supported in Enketo either. Let me check.

**Comment by lognaturel** [comment]
My guess is that you evaluate whatever's in the `text` first and allow `output` there? I agree it wouldn't make sense directly in a `jr:constraintMsg`.

**Comment by lognaturel** [comment]
(A quick Enketo example [here](https://enketo.ona.io/x/#YDlb))

**Comment by MartijnR** [comment]
Oh I'm sorry. Yes, it supports jr:itext() so it's an expression after all, but also accepts literals. That seems weird...

`jr:constraintMsg="This is WRONG."`
`jr:constraintMsg="jr:itext('wrong')"`

This doesn't seem to be consistent because evaluating the first in an XPath evaluator would throw an error. It would have to be `jr:constraintMsg="'WRONG'"` (note the extra quotes). (Enketo doesn't treat itext() as an XPath expression so hence this weird support slipped through without noticing how bad this is)

**Comment by lognaturel** [comment]
Hmm, interesting. I'm not totally sure I'm following why not treating `itext` as an XPath expression leads to this support. In that form, we have `jr:constraintMsg="jr:itext('/constraintMessageError/age:jr:constraintMsg')"` and 
```
<text id="/constraintMessageError/age:jr:constraintMsg">
    <value>Child's age must be between <output value=" /constraintMessageError/ageSet "/> months</value>
</text>
```
What would treating `itext` as an XPath expression lead to in this context? Does Enketo allow other XPath functions or paths in `jr:constraintMsg`?

Maybe we should also tighten down the description of `jr:constraintMsg` and I can file a separate issue for that. It currently says "Specifies the custom message to be displayed when the constraint is violated." In JavaRosa, it looks like `string("whatever constraingMsg is set to")` is passed to the XPath parser.

**Comment by MartijnR** [comment]
This is done during an XSLT transformation that Enketo uses and basically it looks for the presence of the substring 'itext('. It doesn't make much sense. No other functions would work either.

I think we may have to correct the spec but it's not quite "any XPath expression" either, as it should be similar to the limited content we can use for `<label>` and `<hint>`  (either a `ref` attribute or the content of these nodes). Hmm.

**Comment by lognaturel** [comment]
Does that mean something like `jr:constraintMsg="/constraintMessageError/ageSet"` does not work in Enketo?

I'm not quite following what you're referring to with `label` and `hint`!

**Comment by MartijnR** [comment]
I think that is indeed not working in Enketo.

With labels in hints I mean that you can add content either as a reference like this: 

```xml
<label ref="jr:itext('/the/itext/id')"/>
```

or as a literal (correct word to use?) like this: 

```xml
<label>my label</label>
```

With constraintMsg and requiredMsg we're trying to support both uses I think. We're not trying to support things that are not supported in labels such as:

`<label ref="concat(/path/to/my, ' label')"/>`

**Comment by lognaturel** [comment]
Sorry I totally let this drop, I just couldn't figure out what the right way to go would be!

Looking at it with fresh eyes, could we update the spec to say something like "`jr:constraintMsg` can be set to a literal string or be populated by a call to `jr:itext('/path/to/itext')`." I believe this matches Enketo's current behavior and addresses @MartijnR's point in the previous comment about not allowing arbitrary XPath.

**Comment by MartijnR** [comment]
Yes, let's describe this weirdness in the spec.
