### ISSUE TITLE
Proposal: count-non-empty function

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#127]
Exactly as described in [XForms 1.0](https://www.w3.org/TR/2003/REC-xforms-20031014/slice7.html#fn-count-non-empty).

There is a demand for this.

I'll add a link to tests if we decide to add this to the spec.

**Comment by MartijnR** [comment]
I'll close this due to lack of interest so we can focus on more important issues. Please re-open if interested.

FWIW, it is added to Enketo but not exposed to ODK Collect users because forms won't pass ODK Validate (just for a special user that bypasses ODK Validate and doesn't use Collect). Here are the tests: https://github.com/enketo/enketo-xpathjs/blob/master/test/spec/functions-openrosa.spec.js#L757-L785 (though the line numbers will change over time). The XML Document used in the tests is [here](https://github.com/enketo/enketo-xpathjs/blob/master/test/doc.xml)

**Comment by lognaturel** [comment]
I'd prefer to leave open so it's visible! It's the kind of thing that would be good to have in the hopper for when someone has some cycles as development on JavaRosa picks back up.

**Comment by lognaturel** [comment]
Should be in the August JR release so I think adding to the spec can now be marked as a quick win.

**Comment by MartijnR** [comment]
Nice. Thanks. I can create a PR.
