### ISSUE TITLE
Allow naming of multimedia by variable name

### ISSUE THREAD

**Issue by yanokwa** [getodk/xforms-spec#128]
From Ayoub (akakande@gmail.com) and https://groups.google.com/d/msg/opendatakit/_PBKe1uSSZU/EFiZOYdaCgAJ
> Am collecting data from 100 patients daily. for each form am required to take a photo of the patients x-ray forms. I download the data using briefcase, here it creates a media file and dumps all pictures, I have to manually look at image url then search in media folder. I would like to have the photos named by patient name which is a variable within the form so that lay users can tell which photo belongs to which form

**Comment by LloydOBanwart** [comment]
From a user standpoint it would be ideal to designate ODK to name the media file based on survey meta-data. I'd imagine a concatenate of the necessary number of responses. This would run into conflicts when writing file names which are not unique, so some unique suffice/prefix would need to be generated as well, in the event the form developer does not generate a concatenation of variables resulting in unique ids. This could easily happen if it is just ${lastname}, ${firstname}. 

When I manual rename photos from studies in a [batch style (using cmd)](https://benholland.me/tutorials/2011/11/11/rename-multiple-files-using-excel-in-windows.html), I generate names for each photo from the survey data, which provide information. For example I may use 5 responses from the survey to rename a photo from 20384498114323.png to  ${location1}-${location2}-${uniqueID}-${info1}-${info2}.png.

**Comment by MartijnR** [comment]
It would be helpful to propose an XForm syntax for this feature. Hopefully there are already examples out there (Orbeon, IBM, XForms 2.0).

**Comment by MartijnR** [comment]
There is a `<filename>` element in the XForms spec: https://www.w3.org/TR/xforms11/#ui-upload. (It  reveals another deviation by us as we automatically populate the filename as the textContent of the node and that does not seem to be the XForms way). It may allow doing things like:

```xml
<bind nodeset="/data/photo/" calculate="concat('this-','filename.jpg')"/>
...
<upload ref="/data/photo">
     <filename ref="/data/photo"/>
</upload>
```

But this feels wrong to me, because the calculation seems too late (the `<upload>` has already determined what the file name is). 

Another approach might be:

```xml
<bind nodeset="/data/fname/" calculate="concat('this-','filename.jpg')"/>
...
<upload ref="/data/photo">
     <filename ref="/data/photo" value="/data/fname"/>
</upload>
```

or:

```xml
<bind nodeset="/data/fname/" calculate="concat('this-','filename.jpg')"/>
...
<upload ref="/data/photo">
    <filename ref="/data/photo"><output value="/data/fname"/></filename>
</upload>
```

**Comment by lognaturel** [comment]
Further discussion at https://forum.getodk.org/t/naming-pictures-based-on-values-from-the-filled-form/6625
