### ISSUE TITLE
Add support for distance-between() or something similar

### ISSUE THREAD

**Issue by yanokwa** [getodk/xforms-spec#129]
From https://groups.google.com/d/msg/opendatakit-developers/gQrS20_LMBc/GX25qPOcAwAJ

We have support for area() and it'd be nice to get something like distance-between().

**Comment by MartijnR** [comment]
I'm in favor. I just want to propose to name it `distance()` instead, unless people think there is scope for confusion.

Wrt its functionality, how about this description (based on how `area()` works):

_Returns the distance in meters of either a nodeset of geopoints or a single geoshape value or a single geotrace value (not a combination of these) on Earth, in the sequence provided by the 
 points in the parameter. It takes into account the circumference of the Earth around the Equator and does not take altitude into account._

**Comment by lognaturel** [comment]
That sounds great to me, @MartijnR! I agree with `distance()` as the name.

**Comment by lognaturel** [comment]
And just to refresh my memory, we agreed not to namespace custom Xpath functions because XLSForms just passes them through, right?

**Comment by MartijnR** [comment]
I had to look that up as well. We left it [here](https://github.com/opendatakit/xforms-spec/issues/73#issuecomment-272828895). Clearly we are bad, and are in trouble if official XPath specs use the same function name (for functions that do something else). However, it would be harder to shelter users from scary namespaces if we use them for XPath functions (would require more pyxform/etc magic to do - by adding them to the XForm output).

**Comment by meletis** [comment]
We have contributed the distance-between() and several other functions to ODK since last December but I can see those were never merged to the main branch:

https://bitbucket.org/m.sundt/javarosa/commits/7f3677c51d8c65f3ab285c542d6924f6d77775ae

I just remembered there was a public discussion with arguments whether those should be merged or not but I really don't remember what was the final result of this discussion. If I find it, I will post the link here.

**Comment by meletis** [comment]
Oh, thank you, @MartijnR. I saw your last comment after I had posted my comment above. :)

**Comment by muneneg** [comment]
Hi I am adding the `area()` in my xlsform, to calculate the area/size of a plot, the question type am using is `geoshape`. What unit of measure is my `area()` in, Acres/Ha/. 
Thanks

**Comment by MartijnR** [comment]
It it's in square meters. See https://opendatakit.github.io/xforms-spec/#fn:area
