### ISSUE TITLE
Add encrypted form specification

### ISSUE THREAD

**Issue by yanokwa** [getodk/xforms-spec#133]
In building out encrypted forms from @clint-tseng noted that how to encrypt forms isn't described in the spec. Seems like it should be. https://opendatakit.org/help/encrypted-forms has the details.

> The other required element to make this form an encrypted form is the submission tag. Within this tag, the method attribute should always be form-data-post. The action attribute should be the url to which the submission should be posted; this is the ODK Aggregate website url with Aggregate.html replaced by submission. Finally, what identifies the form as an encryted form is the presence of a base64RsaPublicKey attribute. This should be the base64 encoding of the RSA public key that ODK Collect uses to encrypt the symmetric encryption key it creates to encrypt a finalized instance of this form (a different symmetric encryption key is created for every finalized form).

In my testing, the only thing that is required is a `submission` tag with the `base64RsaPublicKey` attribute. @mitchellsundt it seems like `method` and `action` are should have and `base64RsaPublicKey` is a must have. Is that correct? What was the rationale behind having a method and action?

Related: [XForms Submission spec](https://www.w3.org/TR/xforms/#submit)

**Comment by MartijnR** [comment]
will close https://github.com/opendatakit/xforms-spec/issues/21 in favor of this one

**Comment by issa-tseng** [comment]
In terms of the `<submission>` tag itself, it's actually `method` is must have and `action` is should/could have and `base64RsaPublicKey` is could have, right?

**Comment by yanokwa** [comment]
@clint-tseng You are correct. The caveat here is that currently, Collect is not compliant. That is, if you don't have a `submission` tag it'll submit to whatever URL is stored on the device. And if you do have a `submission` tag, it looks for `action` and uses that value to override the URL that the device has.

**Comment by Divya063** [comment]
@yanokwa I would like to take this one

**Comment by lognaturel** [comment]
@Divya063 Great! You should be able to use `opendatakit-bot claim` here as well.

I haven't thought about this deeply but I would tend to add a new section before `Future` called `Encryption`. Notice that this specification is meant to be tool-agnostic so there should be no mention of Collect or Aggregate. Instead, you could use "client" and "server" if necessary.

**Comment by Divya063** [comment]
Thanks, @lognaturel for the information and  I would like to ask whether the XML examples are needed to be completely removed from the Encrypted forms  or not

**Comment by Divya063** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
I believe you are referring to http://docs.opendatakit.org/encrypted-forms/#uploading-finalized-forms. I don't think the XML should be there at all.

In this spec, I would include something like
```
 <submission method="form-data-post"
             action="https://my-server.com/submission"
             base64RsaPublicKey="MIIBIjANB...JCwIDAQAB" />
```
No need to include a full form.

**Comment by Divya063** [comment]
@lognaturel Okay I would remove that section after submitting PR on this issue and thanks again for clarification :smile:

**Comment by Divya063** [comment]
@lognaturel requested changes had been made in the pull request, can you please review it and see if more changes are required?
