### ISSUE TITLE
Prevent the image option the ability to choose image from the device

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/xforms-spec#134]
https://forum.opendatakit.org/t/constraint-and-retrictions/9056

One of our users needs to hide "Choose Image" button in ImageWidget. I think we can do that adding new appearance. Currently we support:

- web
- signature
- annotate
- draw
- align:
- selfie
- and normal image by default

so maybe we should add `take-only` or `image take-only`

What do you think?

**Comment by MartijnR** [comment]
Thanks. The [selfie](https://github.com/opendatakit/xforms-spec/issues/112) discussion includes a similar proposal (at the bottom). I think we want to add the feature you want but we still have to agree on a name. I think take-only is not descriptive enough (because both `selfie` and the new one are meant to capture/take a photo).

**Comment by lognaturel** [comment]
I think `back`, `rear`, `environment` were the ones previously considered.

I'm liking `rear-facing` now that I've thought about it a bit more. I think it makes sense on any kind of device and is pretty commonly used. Now I kind of regret not thinking of `front-facing` for `selfie`.

**Comment by MartijnR** [comment]
We could only document `front-facing` and `rear-facing` (and Collect could support `selfie` as an alias for those users that started using it), if it's not too late.

**Comment by lognaturel** [comment]
Very true. I'd be happy with that.

Should the names be `front-facing-only` and `rear-facing-only` to be extra explicit about the fact that the picker won't be available or do you think the `only` is not necessary?

**Comment by MartijnR** [comment]
Not sure. I think there are use cases for both "preferred default" and "only" option. In browsers, I don't think we can implement this strictly as "only". Hmm.

**Comment by lognaturel** [comment]
Right, with all appearances being just hints, "only" does sound pretty assertive. `front-facing` and `rear-facing` as hints sound good to me. Collect can also accept the `selfie` alias for `front-facing`. @grzesiek2010?

**Comment by grzesiek2010** [comment]
I'm confused... I understand that `front-facing` should be the same as `selfie` but what about this case where we need to show only "Capture Image" button? it should allow us to take a picture using both cameras so it shouldn't be represented as `rear-facing` (it's an appearance for using only a rear camera) right? So what is the appearance for this case?

**Comment by lognaturel** [comment]
I see, you're saying that by analogy to `front-facing`/`selfie` the behavior of `rear-facing` should be to force the use of the rear camera which is a good point. The feature you're describing lets the user choose which camera to use but doesn't allow him/her to pick a photo so that is indeed a bit different.

You suggested `take-only`. What about taking it from the angle of what's different from the current widget and doing something like `no-picker`? Or maybe `force-camera`?

**Comment by grzesiek2010** [comment]
`no-picker` sounds good to me. Can I go ahead and implement this improvement?

**Comment by MartijnR** [comment]
Sorry for detouring this issue earlier, but good to be aware of all 3 requirements. Now, I'd like to propose `camera`, `camera-rear`, `camera-front` instead. In Collect `camera` could open a camera app immediately. In some browsers, there will be still something that most users would call a "picker" (to pick camera apps only in the best case scenario, I think, but also filepickers in most browser/OS combos).

**Comment by lognaturel** [comment]
Aha! That is so much better. Just goes to show it's important to take a step back and look at the big picture. Those fit in well with the idea that the type is `image`. By default, the image can come from a picker or a camera. But the form designer can choose to either request that it come from a camera or that it come from a specific camera.

**Comment by lognaturel** [comment]
Further discussion happened at https://forum.opendatakit.org/t/disable-choosing-an-image-video-or-audio/9338 with agreement on `new` appearance that can combine with `image`, `audio` and `video`.

**Comment by MartijnR** [comment]
I think this is settled and now documented on xlsform.org. Please re-open if not so.
