### ISSUE TITLE
Prevent choosing a recording from audio widget

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#140]
In analogy to #134 and based on @nap2000's proposal [here](https://forum.opendatakit.org/t/disable-choosing-an-image-video-or-audio/9338), only show the record button and not the choose button.

I propose `recorder` for the appearance name (in analogy to `camera`).

**Comment by MartijnR** [comment]
Sounds great to me.

**Comment by lognaturel** [comment]
Further discussion happened at https://forum.opendatakit.org/t/disable-choosing-an-image-video-or-audio/9338 with agreement on `new` appearance that can combine with `image`, `audio` and `video`.

**Comment by MartijnR** [comment]
I can write this in the XLSForm documentation. Will wait until approval is confirmed.

**Comment by MartijnR** [comment]
moved to https://github.com/XLSForm/xlsform.github.io/issues/108
