### ISSUE TITLE
Clarify how the "primary instance" is identified

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#143]
As far as JavaRosa is concerned, the "primary instance" is the top-most instance. @MartijnR is this also the case in Enketo? Can we codify this? I think it's an important thing to have clearly defined!

**Comment by MartijnR** [comment]
👍 Yes, it's the first instance, officially: https://opendatakit.github.io/xforms-spec/#instance We should definitely repeat that in the primary instance section intro.

**Comment by lognaturel** [comment]
Ohhhh, hiiiiii! Must be Friday. 😖

I promise I looked for that!
