### ISSUE TITLE
Remove depend() from the spec

### ISSUE THREAD

**Issue by alxndrsn** [getodk/xforms-spec#145]
Does anybody know what [`depend()`](https://opendatakit.github.io/xforms-spec/#fn:depend) does?  If not, it should be removed from the spec :¬)

**Comment by MartijnR** [comment]
Am in favor, since I don't know what to use this for. 

If there is a fear that people may be using this (but without finding out what they're using it for), clients could keep the implementation just to be sure.

**Comment by lognaturel** [comment]
Sounds great to me, too!
