### ISSUE TITLE
Add example of guidance hint (body)

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#183]

**Comment by lognaturel** [comment]
I would say the example in https://opendatakit.github.io/xforms-spec/#languages is sufficient.

I think this issue was created in reaction to my botched pyxform implementation. That wasn't caused by insufficient docs, just by me not going back to review them!

**Comment by MartijnR** [comment]
Yes, true. I was actually initially thinking that we indeed did have a way to describe guidance hints in the `<body>` without using `itext()` (as in your initial PR). But I think you're right that it needs `itext()`.

So this can be closed :)
