### ISSUE TITLE
Specifying fields to send via SMS

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#188]
A Long Time Ago™️, a specification was developed by the OpenRosa working group to specify fields that should be sent via SMS and structuring an SMS submission: https://bitbucket.org/javarosa/javarosa/wiki/SMSSendingAPI

ODK Collect users have long wanted this functionality (https://forum.opendatakit.org/t/send-submissions-via-sms/12166/55) and @joeldean is currently making slight modifications to the underlying spec and completing the implementation.

I realized when discussing XLSForm support at https://github.com/XLSForm/pyxform/issues/207#issuecomment-394521060 that SMS support is not included in the spec here. I think it probably should be?

**Comment by MartijnR** [comment]
Yes! Is this the same SMS feature as what was supported by formhub (and now presumably Ona) (@ukanga)?
