### ISSUE TITLE
Clarify Function types, operand conversion, result types

### ISSUE THREAD

**Issue by adammichaelwood** [getodk/xforms-spec#189]
https://opendatakit.github.io/xforms-spec/#fn:coalesce

I tried an integer, which worked. I assume other types would work as well, though I haven't tested.

**Comment by MartijnR** [comment]
Thanks Adam. I think it's correct to specify the arguments as string in the spec as they will be cast to strings by the XPath evaluator, like `if()` for example

However, this issue reveals other functions that should equally specify string arguments. So with your permission, I'd to change this issue to correcting:

* `concat()`
* possibly others

**Comment by adammichaelwood** [comment]
I assume you're just being polite, since you don't need my permission. 

> correct to specify the arguments as string in the spec as they will be cast to strings by the XPath evaluator
> other functions that should equally specify string arguments

I don't know enough about XPath to have a *well-informed* opinion here, but this seems... incomplete, at least.

A consumer of this spec who is building XForms (or form validation tools, I guess) would need to know that these functions can accept [any stringifiable (?)] type... right?

But someone implementing the spec in a form-rendering library would need to know that the inputs and outputs are strings... yes?

Is there a concise way of communicating all of that information for these functions?

**Comment by MartijnR** [comment]
:)

Yes, good point. I think we should perhaps divide the functions into Number Functions, String Functions, Node Set Functions, Boolean Functions, and then explain what that means in terms of type conversion of operands and result types (or link to the XPath spec sections that explain this). 👍 This is what the XPath 1.0 spec does as well.

**Comment by adammichaelwood** [comment]
That makes sense to me.

**Comment by MartijnR** [comment]
@lognaturel are you on board with this as well?

**Comment by lognaturel** [comment]
Sounds like a great idea. 👍
