### ISSUE TITLE
add format-date-time()

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#20]

**Comment by alxndrsn** [comment]
What's the deal with this?  Should it be part of the spec?  How would it differ from `format-date()`?

**Comment by lognaturel** [comment]
Arg, I just ran into this. Looks like in JavaRosa-land `format-date` suppresses the time component and `format-date-time` includes it. 

I'd be in favor of modifying the JR implementation and not documenting/deprecating `format-date-time`.

**Comment by MartijnR** [comment]
That sounds good to me. So, we should update documentation for format-date() to have a `dateTime` argument?

**Comment by lognaturel** [comment]
That seems to make sense, right? It can take either a `date` or a `dateTime`. Is that what Enketo allows currently?

What about a `time`?

**Comment by MartijnR** [comment]
I think supporting `date` and `time` arguments is better done in their own functions with fewer formatting options (excluding options that deal with the missing time/date information). Maybe we wait until there is a need for those?

**Comment by lognaturel** [comment]
The currently-documented function is called `format-date`. Are you suggesting changing that to `format-date-time`? I think that would be ok.

Do these functions map to any existing standard? XSLT, maybe? https://www.w3.org/TR/xslt20/#format-date The identifiers are different and I don't know whether those are meant to correspond to any existing standard.

**Comment by MartijnR** [comment]
I think we should probably document both `format-date-time` and `format-date`. The difference between them is the data type of the argument and removing the 5 time-related formatting arguments (`%H,%h,%M,%S,%3`). As with other XPath functions it seems reasonable to expect that the XPath evaluator tries to cast the argument to the right type. However, we should probably encourage users to pass the right argument to the right function (by documenting both) to avoid differences in dealing with timezones.

Good find of the XLST function! Indeed, we're deviating, but I guess it's too late to fix. Also the XLST name `format-dateTime` is probably better than `format-date-time` because the datatype is `dateTime`, but I vote to just leave it as `format-date-time` because it has been in use already and because we're deviating anyway.
