### ISSUE TITLE
Inconsistent odk namespace

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#203]
https://github.com/opendatakit/xforms-spec/commit/62ed5d8b68a9159f0c0de33fdea17ab45853e41a introduces the namespace commonly abbreviated to odk as `http://opendatakit.org/xforms`.

In fact, it was previously defined in Aggregate and pyxform as `http://www.opendatakit.org/xforms`: https://github.com/opendatakit/aggregate/commit/604eae3f0ad184a0e1fc80ccd0933dc597bc1279 (7 years ago), https://github.com/XLSForm/pyxform/commit/7decb0cf05e65e499f4a035747dd3a4e2f7c1675.

I see Enketo uses both:  https://github.com/enketo/enketo-core/search?q=http%3A%2F%2Fopendatakit.org%2Fxforms&unscoped_q=http%3A%2F%2Fopendatakit.org%2Fxforms

JavaRosa/Collect doesn't enforce namespace on everything. This issue is coming up because it does enforce it on SMS attributes and expects `http://opendatakit.org/xforms` but https://github.com/XLSForm/pyxform/pull/214 produces the `http://www.opendatakit.org/xforms` namespace.

I think the mistake here is in the spec and it should be updated to `http://www.opendatakit.org/xforms`. This would be safe for ODK core tools. @MartijnR, @ukanga, @yanokwa?

**Comment by lognaturel** [comment]
Ah yes, I see @yanokwa has marked this as high priority. It is blocking the Collect release so hopefully we can get to a swift resolution!

**Comment by yanokwa** [comment]
The non-www namespace is relatively new on Enketo, so I'm hoping it's not too much trouble to revert. 
* enketo-xslt https://github.com/enketo/enketo-xslt/search?q=%22http%3A%2F%2Fopendatakit.org%2Fxforms%22&unscoped_q=%22http%3A%2F%2Fopendatakit.org%2Fxforms%22
* enketo-validate https://github.com/enketo/enketo-validate/search?q=%22http%3A%2F%2Fopendatakit.org%2Fxforms%22&unscoped_q=%22http%3A%2F%2Fopendatakit.org%2Fxforms%22
* enketo-core https://github.com/enketo/enketo-core/search?q=%22http%3A%2F%2Fopendatakit.org%2Fxforms%22&unscoped_q=%22http%3A%2F%2Fopendatakit.org%2Fxforms%22

**Comment by MartijnR** [comment]
Ah, right, so all old pyxform-created forms used `www`. Definitely makes sense to make that the official ODK namespace then. It's not too late. I will change in Enketo code (and in the worst case, after checking with Esri (that paid for it and may have started using it) just support both). That should not be a big deal.

**Comment by lognaturel** [comment]
Thank you, @MartijnR, for getting on this so quickly.
