### ISSUE TITLE
Revisit language about dynamic jr:count

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#206]
The description of `jr:count` currently includes the following language:

> Note: It is problematic to implement this in a truly dynamic fashion, i.e. when the value changes, to update the number of repeats

This should either be expanded to explain why it's problematic or perhaps changed to a warning. As far as I can tell, a fully-dynamic implementation is fine but some expressions could lead to repeats being added infinitely. That just means a form designer would need to be careful when writing their expressions. 

Related: https://forum.opendatakit.org/t/xls-form-repeat-select-one-question-until-a-is-selected/15318/16

**Comment by MartijnR** [comment]
I agree! I think it can just be removed.
