### ISSUE TITLE
Make GeoShapeData / GeoPointData more flexible to include additional geo data

### ISSUE THREAD

**Issue by OlivierVernin** [getodk/xforms-spec#216]
This is a request to discuss adding some flexibility on the GeoShape/GeoPointData format. The current format is `-6.668710000000001 106.91277 821.2 1.7; <another point>; <and another point>`. 

We would like javarosa to allow additional data to be attached for each point so that the points could carry more contextual data on how they were recorded while still supporting the area() or distance() functions. That additional information would enable advanced surveying capabilities within ODK collect.

The contextual data should be rather flexible with minimum constraint to let each application come up with a best fit format. To give an example of those data in the context of [our work at meridia](http://meridia.land/), there is a nonexhaustive list:
- a uuid v4 generated when the point was recorded
- the method used to record the point: tablet gps, bluetooth gps, gps with rtk capabilities, drawn or snapped to an existing point...
- (depending on the method) the uuid of the point it was snapped to
- (depending on the method) an attached raw gps file that was downloaded from the gps device
...
Currently, our internal format is to add a json dictionary at the end of each point such as:
`-6.668710000000001 106.91277 821.2 1.7 {"uuid": "12344....", "method": "rtk", ...};...`

Focusing on JavaRosa modification, our suggestion would be to have the GeoPointData accept the following format `<double> <double> <double*> <double*> <string*>` where only the 2 first double are mandatory. Altitude, accuracy and the additional string would be optional.

In the coming weeks, we will propose an implementation of this modification via a PR. In the mean time feel free to feedback.

**Comment by yanokwa** [comment]
@OlivierVernin This is a spec level decision so I'm moving the issue from JavaRosa. My initial take on this is this will cause a lot of downstream problems.

My recommendation is to start a conversation at https://forum.opendatakit.org/c/development about the high-level problem you want to solve. My guess is that we might be able to do what with a new and more standard data type (e.g., GoeJSON)

**Comment by OlivierVernin** [comment]
[conversation started on the ODK forum](https://forum.opendatakit.org/t/make-geoshapedata-geopointdata-more-flexible-to-include-additional-geo-data/16861)

@yanokwa thank you for the quick comment
