### ISSUE TITLE
Add documentation for the new `normalize-space` XPath function in Javarosa

### ISSUE THREAD

**Issue by jkpr** [getodk/xforms-spec#242]
A recent pull request in Javarosa for the normalize-space function requires documentation for users. Its definition is here: https://www.w3.org/TR/1999/REC-xpath-19991116/#function-string-length

I recommend it be placed with other string functions at:
https://github.com/opendatakit/xforms-spec/blob/gh-pages/_sections/30-bindings.md#xpath-functions

**Comment by lognaturel** [comment]
Since this is part of XPath 1.0 and it's been discussed on the forum, it's ready to add to the spec if you want to do it!
