### ISSUE TITLE
Remove repeat ref deviation?

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#251]
I thought there was an issue or discussion about this somewhere but cannot find it.

In any case, I think we may be ready to remove this from the spec due to recent pyxform changes (and just silently keep supporting it for old forms).

**Comment by lognaturel** [comment]
Seems like the right time to do it. I think it would be good to have an explicit (short) explanation of the change in the changelog (which we have ignored for some time 😫).
