### ISSUE TITLE
min() and max() comply with XPath 2.0, not XForms 1.0

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#272]
As we accept multiple parameters.

https://github.com/getodk/xforms-spec/issues/233

https://github.com/getodk/javarosa/blob/be1c28ea13585a5c43e184132ddbb8abf47a4e42/src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java#L329

**Comment by MartijnR** [comment]
Since we have no XPath 2.0 functions (and the spec is a weird doc), I propose we refer to XPath 3.0 instead: https://www.w3.org/TR/xpath-functions-30/#func-min

**Comment by MartijnR** [comment]
pinging @tiritea in case this affects your app's implementation

**Comment by tiritea** [comment]
Ta. Presently I do whatever libxml2 does... :-)
