### ISSUE TITLE
Correct description for uuid() with argument

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#274]
As @alxndrsn discovered, a GUID and UUID are the same and should be 128 bits, so it probably say something like:

_Without arguments, it returns a random RFC 4122 version 4 compliant UUID. With an argument it returns a random string with the provided number of characters._

**Comment by MartijnR** [comment]
Javarosa: https://github.com/GetODK/javarosa/blob/59611cc0755dfbaf6631866ff15d6a9a516df704/src/main/java/org/javarosa/core/util/PropertyUtils.java#L60-L66

It would have been better to not support an argument for uuid() and create a new function for a random string of a custom length instead. But presumably, we'll have users that are using an argument.

**Comment by lognaturel** [comment]
> It would have been better to not support an argument for uuid() and create a new function for a random string of a custom length instead. But presumably, we'll have users that are using an argument.

Agreed. Unfortunately, the `uuid(len)` variant has been there since the beginning of time.
