### ISSUE TITLE
Add pulldata()

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#3]
Would like to come up with a more XForms and XPath-compliant way of doing this. Will propose something if nobody beats me to it.

**Comment by MartijnR** [comment]
https://groups.google.com/forum/#!topic/opendatakit-developers/9_VZoe7crVY

**Comment by lognaturel** [comment]
Is this now #50?

**Comment by MartijnR** [comment]
Yes, it is. Once we have agreed on a way to add external XML data, we can extend it for CSV data (new proposal), and after that there would be a nice way to add pulldata to the spec as an actual XPath function (as well as potentially other XLSForm or XPath shortcuts to easily query such data).

I'll change the topic.

**Comment by MartijnR** [comment]
This is now dependent on #88. We could add it already for XML data but since pulldata() is mostly used for CSV data is would be better to wait until we've agreed on a way to add CSV data first.

**Comment by MartijnR** [comment]
closed by https://github.com/opendatakit/xforms-spec/pull/230
