### ISSUE TITLE
selected-at is 0-based

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#30]
thanks @tinok

**Comment by MartijnR** [comment]
dealt with by #33

**Comment by lognaturel** [comment]
Fun Github feature -- if you use [keywords for closing issues](https://help.github.com/articles/closing-issues-via-commit-messages/) in your commit messages (like you did) or PR title/body, the corresponding issues will be closed automagically when the merge happens!

**Comment by MartijnR** [comment]
Oops yes, I forgot I had done that. Fun indeed!
