### ISSUE TITLE
merge relevant improvements from commcare spec

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#33]
https://github.com/dimagi/xform-spec

**Comment by mberg** [comment]
What's the high level differences here?

**Comment by MartijnR** [comment]
I was referring to just lots of edits and additions that apply to ODK as well.

Major _differences_ of CommCare with ODK are: 
- [external data](http://dimagi.github.io/xform-spec/#secondary-instances---external) (CommCare similar to Enketo => `<instance src="jr://somesrc"/>`)
- [actions](http://dimagi.github.io/xform-spec/#actions)
- [meta data](http://dimagi.github.io/xform-spec/#metadata)
- more comprehensive XPath predicate support (I think)
- more native XPath functions
- fewer custom XPath functions 
- more namespace usage (and probably better support for this)
- no geotrace and geoshape datatypes
- not sure: [external applications ](http://dimagi.github.io/xform-spec/#external-applications)

**Comment by MartijnR** [comment]
Todo:

* [x] orx:version instead of version acceptable?
* [x] xsd:string, xsd:integer etc acceptable?
* [x] make sure all 'badges' are removed
* [x] section on external app has reference - may need another writer if different from CommCare.
* [x] depending on prev point, check with bind data type 'intent' is correct
* [x] check if function double() is supported
* [x] check if `abs(), ceiling(), floor(), log(), uppercase(), contains(), starts-with(), ends-with(), translate(), replace()` are not supported (assumed they were not but they are in CommCare)
* [x] check if uuid() description is correct (probably is not!) 
* [x] property() description
