### ISSUE TITLE
Include form_logo.png feature in documentation

### ISSUE THREAD

**Issue by tinok** [getodk/xforms-spec#34]

**Comment by MartijnR** [comment]
form_logo.png = :sparkles:magic:sparkles:

yes, this XForm-manifest-driven feature should be documented.

**Comment by tinok** [comment]
@MartijnR looks like you have found a new friend who doesn't want form_logo.png to be in the documentation!

**Comment by MartijnR** [comment]
Haha, yes but it is good to be strict in the long run. I've centered media labels in Enketo now, so we can fake it and probably be similar to Collect (and in any case, won't remove the feature from Enketo). You could consider it a KoBo Enhancement. We could also figure out a proper XForm (and XLSForm) syntax for it (e.g. in conjunction with a translatable form title).
