### ISSUE TITLE
barcodes should be more permissive?

### ISSUE THREAD

**Issue by chrislrobert** [getodk/xforms-spec#4]
The barcode data type is currently listed as "string consisting only of alphanumeric characters". However, using QR codes some users are undoubtedly storing URLs and other strings that contain non-alphanumeric characters. Is there a reason to restrict the barcode datatype to alphanumeric?

**Comment by MartijnR** [comment]
Yes, good point. Is barcode the same as string in javarosa? (In Enketo it is)

**Comment by chrislrobert** [comment]
Everywhere I see it referenced in JR, it is treated the same as BINARY.
It's untyped for some purposes, and then assembled as StringData. It sure
looks like JR takes anything in that field.

**Comment by MartijnR** [comment]
Thanks. It would seem that 'as string' would work here then.
