### ISSUE TITLE
add auto-submit and auto-delete attribute on submission element

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#44]
according to final agreeement here: https://groups.google.com/forum/#!topic/opendatakit-developers/wqFe7JpO9ZI

TL/DR:

```xml
<submission orx:auto-submit="false">
```

**Comment by yanokwa** [comment]
For auto-delete, we should also add: `<submission orx:auto-delete="false">`

**Comment by lognaturel** [comment]
Conversation is now at #100.
