### ISSUE TITLE
Proposal: Randomizing nodesets

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#51]
Add support for a custom randomize() function, that takes a single nodeset as parameter.

[earlier discussion on dev forum](https://groups.google.com/forum/#!searchin/opendatakit-developers/randomize%7Csort:relevance/opendatakit-developers/plutkYCqWB4/QAcV1SZsBQAJ)

As in any XPath function, there would be no restrictions on its use, but the use case that triggered this proposal is to randomize select and select1 options like this:

```xml
<select1 ref="/form/state">
    <itemset nodeset="randomize(instance('choices')/states/state)">
        <label ref="name"/>
        <value ref="value"/>
    </itemset>
</select1>
```

**Comment by lognaturel** [comment]
Who should be involved in the discussion on whether or not to move this forward? I'm surprised that there isn't something like this in XPath or in XForms but I'm not seeing anything. Seems reasonable to me.

**Comment by lognaturel** [comment]
Oh, and the discussion on the collect side (opendatakit/collect#237) mentions keeping track of the order. That's to be able to tell if order affected responses, right? What could that look like on the spec side?

**Comment by yanokwa** [comment]
I looked around a bit and [Randomizing the Responses to a Survey Question in XForms](https://www.ibm.com/developerworks/community/blogs/JohnBoyer/entry/randomizing_the_responses_to_a_survey_question_in_xforms29) is the closest thing I can find. Seems cumbersome. 

I've also looked at a couple of survey tools (e.g., Survey Monkey, Survey Gizmo, Qualtrics, CS Pro) and they don't track ordering so I think we should punt on that.

**Comment by yanokwa** [comment]
Given some of the earlier discussions, it seems reasonable to add a randomize() custom function to the spec. @chrislrobert @mberg @spatialdude @mitchellsundt. Penny for your thoughts?

**Comment by MartijnR** [comment]
Wow, that IBM method blows my mind. Action/setvalue is certainly powerful (this is the replacement for preload items that CommCare is using). Nice find. 

I agree with punting on recording the order and going with just randomize(/path/to/nodes) for now.

Adding @dorey as well.

**Comment by mitchellsundt** [comment]
I believe most analysts would want to know how the set is randomized, not just that it is randomized.  If you can't reconstruct how it is randomized, then you can't verify or disprove correlations.  With that in mind, you probably want to first have a calculated field:

once(random()) that is stored in the form as, e.g., ${choiceRnd}, then have 

... randomize(instance('choices')/states/state, ${choiceRnd})

and have a well defined way to reconstruct the choice order from that random seed value (being careful for choiceRnd truncation / rounding during transmission/conversion). So that an analyst could reconstruct order if they wanted to.

FYI: The last pull from CommCare that I brought in had at least some of the changes for action / setvalue support. Not sure what was missing/left-to-do, but someone could wade through and see what would need to change to bring that fully into ODK Collect.

**Comment by MartijnR** [comment]
That would be a very interesting way of making it reproducible without having to store/send a complete list in the submission. I'm fine with that.

 (It would also still allow us to implement the simple 1 parameter randomize() function, if desired but I guess that may not make much sense unless we split this in 2 phases.) 

Any suggestions for an algorithm to randomize a list from a single random number value?

**Comment by lognaturel** [comment]
@MartijnR I think we should move forward on two variants -- `randomize(<nodeset>)` and `randomize(<nodeset>, <seed>)`.

I propose using Fisher-Yates for shuffling in both cases. If a seed is provided, that seed is passed to the pseudo-random number generator. I propose using the Java algorithms for seeded PRNs: https://docs.oracle.com/javase/7/docs/api/java/util/Random.html#nextInt(int) and https://docs.oracle.com/javase/7/docs/api/java/util/Random.html#next(int). The algorithms are easily accessible and implementable in other languages. As long as those are consistently implemented it will be possible to reconstitute the sequence meaningfully across compatible platforms.

We can provide some advice on a seed range based on the number of options.

**Comment by lognaturel** [comment]
> We can provide some advice on a seed range based on the number of options.

This is non-trivial to get an even distribution of permutations, I think. Something like `decimal-date-time(now())` might be a better bet?

**Comment by MartijnR** [comment]
Thanks for moving this forward. Does the variant with the seed produce the same result every time the same seed is used?

**Comment by lognaturel** [comment]
Yes, exactly. The same sequence of random numbers for swaps will be generated which will result in the same permutation. In fact, http://timothygu.me/knuth-shuffle-seeded/ is exactly what I had in mind (though I don't know whether the seed is used in the exact same algorithm as I proposed or not; it just has the same properties).

**Comment by MartijnR** [comment]
Perfect. Thanks. Ready for documentation and implementation then! I could create a PR.

**Comment by lognaturel** [comment]
Fabulous. 🙏🎉✨

**Comment by MartijnR** [comment]
Whoever ends up implementing this first, should kindly share some tests with seeded shuffles, so we can double-check that our implementations match, and find errors.

**Comment by lognaturel** [comment]
@MartijnR as I was exploring the spec/reality fault line I discovered that `itemset` currently expects `nodeset` to be an XPath path and not an arbitrary expression. Setting it to an expression results in an error.

Do you see this as an artificial requirement? I don't see any example from W3C XForms where the `nodeset` attribute is set to anything that's not a path. I haven't looked too deeply yet but the assumption seems pretty deeply baked into JR.

**Comment by MartijnR** [comment]
Ah interesting. I hadn't thought of that.

https://www.w3.org/TR/2001/WD-xforms-20010828/slice7.html#ui-common-nodeset

It's a _binding expression_  (aka _XPath addressing expression_) as opposed to a _computed expression_

https://www.w3.org/TR/2001/WD-xforms-20010828/slice3.html#def-binding-expression

This is what I found about binding expressions: https://www.w3.org/TR/2003/REC-xforms-20031014/slice7.html#expr-binding-expression

I think we're okay, but will try to parse this further...

**Comment by MartijnR** [comment]
I got a little lost... It's an _XPath PathExpr_ (as described in the last link). I found this to describe a PathExpr:

https://www.w3.org/TR/1999/REC-xpath-19991116/#NT-PathExpr

`randomize(/a/path)` would no longer be considered a LocationExpr, but I think it would be a type of FilterExpr (the type of FilterExpr that is a PrimaryExpr). By that logic all expressions that return nodesets would be allowed.

If we could randomize inside a predicate we could eliminate any doubt, but I don't see how we could do this. Otherwise, we could consider custom attributes on itemset. 

Unless others have objections, I'd be fine with accepting any expression (in a nodeset attribute on an `<itemset>`) that returns nodesets (and therefore leaving the spec as is).

**Comment by lognaturel** [comment]
Hmm, ok, I am following your references and I think you're right that the W3C XForms intent is that anything that evaluates to a nodeset can be used as a `nodeset`.

Sadly this will likely not be usable in JavaRosa any time soon.

**Comment by lognaturel** [comment]
Looks like I was overly pessimistic. With some fresh eyes on JR curtesy of @ggalmazor JR will have support in the next release! It may be narrow support for randomize for now rather than full support for any expression that evaluates to a nodeset but either way it will be something.
