### ISSUE TITLE
Rename repo to odk-xforms

### ISSUE THREAD

**Issue by yanokwa** [getodk/xforms-spec#54]
I propose we rename the repo to "odk-xforms". Note the "s" at the end and dropping of spec. This matches what the W3C does.

**Comment by MartijnR** [comment]
Not a big deal, but I like more descriptive repository names, i.e. with "spec" or "specification" in them. "odk-xforms" sounds more like a repository for sample/demo XForms to me.

Note that any links to https://opendatakit.github.io/odk-xform-spec/ will probably [not be directed](https://help.github.com/articles/renaming-a-repository/) to the new URL.

**Comment by lognaturel** [comment]
I think having "spec" in the name is good. I do think the spec name should have an "s" to match the W3C spec naming, what do you think @MartijnR? We can be consistent about that usage without renaming the repo I suppose.

**Comment by MartijnR** [comment]
Yes, "odk-xforms-spec" is fine with me.

**Comment by lognaturel** [comment]
Is it worth changing the repo name do you think?

**Comment by MartijnR** [comment]
Oh, sorry, I didn't read that. No preferably not changing the repo name indeed, so that links don't break.

**Comment by yanokwa** [comment]
I know this is pendatic, but a spec repo that doesn't comply to the name of the spec is not a great sign. Also, it's better to break links now when no one is using the spec than later when this repo is wildly popular...

**Comment by MartijnR** [comment]
;) Renaming repo to "odk-xforms-spec" is fine with me. Not a big deal.

**Comment by yanokwa** [comment]
And now that we agree on changing the name, I propose 'xforms-spec' for the repo. We are already in the odk namespace (e.g., the collect repo is called collect, not odk-collect). What say ye?

**Comment by MartijnR** [comment]
I say "yay"

**Comment by yanokwa** [comment]
Done.
