### ISSUE TITLE
Clarify namespaces

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#55]
@lognaturel writes:

> I know the document pre-supposes a good working understanding of XML but I'm wondering whether it might be worth linking to a quick resource about namespaces along with introducing this (good) change? It might also be good to explain things like the value of having separate OpenRosa XForms and OpenRosa javarosa namespaces as defined in this example.

**Comment by lognaturel** [comment]
I got a little more background from @MartijnR and will take a stab at writing up what I've learned.

The key thing is that namespaces were introduced to identify additions not in the XForms 1.0 spec but were not used consistently. `jr:` was the originally chosen namespace but it unfortunately is tied to JavaRosa which is a specific implementation. `orx:` is an implementation-agnostic replacement.

**Comment by MartijnR** [comment]
Yes, the way I see it, the key is for them to be namespaced with anything. The actual namespace value is less important, as long as we can limit the amount of different namespaces somewhat. The JavaRosa namespace could identify the origin of a particular extension which seems fair enough. Though ideally, in the future, we agree on extensions _before_ they are implemented and then use the openrosa.org/xforms namespace.
