### ISSUE TITLE
clarify what today() and now() return exactly

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#56]
@lognaturel writes:
> Would be good to explicitly call out the format and/or say it's DateUtils.roundDate(new Date()), same with now()...

It should be clear what should be returned by these functions at least for datatypes: date, time, datetime, integer, decimal (and string? - that one scares me).

This should be done in a language-agnostic manner (no references to Java or JavaRosa).

**Comment by lognaturel** [comment]
Oops, yes, you're right about it needing to be language-agnostic.

**Comment by lognaturel** [comment]
XForms equivalents are [`local-date()`](https://www.w3.org/TR/xforms/#fn-local-date) and [`now()`](https://www.w3.org/TR/xforms/#fn-now), both return strings. But I agree that's not as useful. Were you thinking it could be written as something like "a date object as defined by the implementation language's standard libraries"?

**Comment by MartijnR** [comment]
Oh totally didn't realize that it is in XForms. 

Your "date object" suggestion makes sense to me. I think XPath has no way of calculating `today() + 1` correctly, because it cannot recognize datetime strings as special strings. 

So maybe we need to describe in the spec how a datetime string is converted to a "Number" and "String" type (in XPath terminology) internally in the XPath evaluator, so independent from the datatype of the question.

**Comment by lognaturel** [comment]
Err, right. XPath. So `today()` and `now()` are intended to be custom XPath functions rather than XForms functions. Given their usage, I guess that makes sense. The relationship between XPath and XForms is also something that might merit a sentence or two.

XPath does define [a format for date and time](https://www.w3.org/TR/xpath-functions/#date-time-values). I didn't totally understand what you said about `today() + 1`. Xpath defines the [add-dayTimeDuration-to-dateTime)](https://www.w3.org/TR/xpath-functions/#func-add-dayTimeDuration-to-dateTime) function for that behavior which backs `+` for a duration and a dateTime. Do you mean that in the context of this sub-spec, the `date-time` and `duration` types aren't defined which is why that can't be supported?

**Comment by MartijnR** [comment]
(I'm just thinking out loud, this date/datetime stuff is very confusing to me).

I meant that an XPath 1.0 evaluator doesn't have a built-in date-like type (it only has Number, String, Nodeset and Boolean, and converts string values to one of these depending on the type of function/operator). So if you're sending an expression such as `"now() + 1"`, which I think we support in ODK, to a pure XPath 1.0 evaluator, with XForms 1.0 now() support,  you'd get response `NaN`. Note: the actual datatype (in `<bind>` of the question this expression belongs to is not relevant.

So I wonder if we could write in our spec:

> * now() as in [XForms 1.0](https://www.w3.org/TR/2003/REC-xforms-20031014/slice7.html#fn-now)
> * today() as now() but without the 'T' and time component.
> 
> [And the real ODK customization:]
>
> In addition, it is possible in ODK XForms to perform arithmetic and comparisons with date and datetime strings whereby each is converted to [rounded? tbc] days since the epoch (1970-01-01T00:00:00Z).


Would that correspond to how JavaRosa does things, or have I misunderstood? 

Maybe a more realistic example would be the expression `". < today()"`, where the XPath evaluator has to recognize that "." is a date or datetime. This is a custom thing we do.

P.S. in hindsight, I think we should have obligated users to wrap dates in date() for comparisons and arithmetic.

**Comment by igalchuk** [comment]
Hi @MartijnR ,

Do you have any examples how to write a constrain to validate the date input against the current date? I can't figure out how to use today() function, it doesn't seem to work.

Thanks,
Iryna

**Comment by MartijnR** [comment]
_should_ be `". < today()"` for a date before today (but may be broken)

**Comment by igalchuk** [comment]
Unfortunately it is not working. The expression  ". = > today()" takes tomorrow and other days in the future and triggers an error if I enter today's date or the day from the past. The expression ". = today()" triggers the error message regardless of the date input (future day, day from the past or today).

**Comment by MartijnR** [comment]
Thanks. Please report bugs in the repo of the tool you are using. I know you are referring to Enketo, so do this [here](https://github.com/kobotoolbox/enketo-express) (but this is a known issue).
