### ISSUE TITLE
clarify property() function

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#57]
To be done in a way that we can present this as an XPath function (regardless of how exactly it's implemented in JavaRosa or Enketo (it is not)). This is not easy imo.

It would be easy if/once we replace preload items with an external session instance like CommCare because in that case `property(PROP)` is just a shortcut for obtaining `instance('session')/PROP` or something similar.

**Comment by MartijnR** [comment]
@lognaturel writes:
> Sounds like it might be a candidate for deprecation?

Yes, that would be good. And not document it at all perhaps.

**Comment by lognaturel** [comment]
I think removing it from the spec for now is fine. It's ok to have things in JavaRosa that aren't part of the spec. Ideally in the near future JR will get its own documentation that amends this spec with any relevant implementation details and extra features.

When you suggest replacing "preload items with an external session instance like CommCare ", you mean having an external XML document that holds session information and which is retrieved as an external instance as per #50, is that correct?

**Comment by MartijnR** [comment]
What are the exact property() parameter values that JavaRosa supports?

**Comment by lognaturel** [comment]
Oops, totally missed this. [Here](https://github.com/opendatakit/javarosa/blob/3eb73b5c8c1d56b9bd635b1aca6a8e9ab1051fa9/core/src/org/javarosa/xpath/expr/XPathFuncExpr.java#L386) is the relevant code, I believe. It accepts a single string parameter which represents the name of the desired property managed by the `PropertyManager`. I really don't think it belongs in this spec.

And to confirm, you are talking about #50 as a possible way to hold session information, right?

**Comment by MartijnR** [comment]
Thanks. I see [these](https://github.com/opendatakit/javarosa/blob/3eb73b5c8c1d56b9bd635b1aca6a8e9ab1051fa9/core/src/org/javarosa/core/services/properties/JavaRosaPropertyRules.java#L39-L48):

* "DeviceID"
* "cur_locale"
* "logenabled", returning either "Enabled" or "Disabled"
* "jr_openrosa_api"

> I really don't think it belongs in this spec.

Yes, I think I agree. I did coincidentally see a query from Esri about this function and I've asked them for their use case for it (that is not equally well met by preload items). Maybe there is one.

> And to confirm, you are talking about #50 as a possible way to hold session information, right?

Yes

**Comment by MartijnR** [comment]
To be removed as part of #189 fix.
