### ISSUE TITLE
Clarify whether this is a subset of XForms 1.0 or 1.1

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#60]
In the intro paragraph, the spec is described as a subset of XForms 1.0 but the link goes to the 1.1 spec. Should it be treated as a subset of XForms 1.0 or 1.1?

**Comment by MartijnR** [comment]
Shall we do 1.0? 

https://www.w3.org/TR/xforms/#intro-diffs

We can go either way, I think. Not really using any of the XForms 1.1 changes as far as I can see. `if()` and the `action` attribute on submission are deprecated in 1.1 but still supported.

**Comment by lognaturel** [comment]
Yes, that sounds right. We can work on Turing completeness another day. 😄

**Comment by MartijnR** [comment]
After working on #139, I found 2 functions we're using that are in 1.1 and not in 1.0, so now I wonder if we should use 1.1 as our partial basis after all... 

* current() https://www.w3.org/TR/xforms11/#fn-current
* random() https://www.w3.org/TR/xforms11/#fn-random

We deviate slightly from random() by not supporting a (seed) parameter though.

**Comment by lognaturel** [comment]
Or perhaps we're based off of 1.0 with some functions adopted from 1.1?

The `random(boolean seed)` variant seems really odd to me. Specifying a numeric seed could perhaps seem helpful but a boolean? What's an unseeded random number anyway?

**Comment by MartijnR** [comment]
yes, weird that that is a boolean indeed. 

Sure, we can do 1.0 with some 1.1 functions.
