### ISSUE TITLE
How should new custom functionality be namespaced?

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#73]
I believe the idea has been to use the http://openrosa.org/xforms namespace, generally prefixed `orx`, for any new custom functionality. It occurs to me that it might be more pragmatic to just keep using `jr` and aim for consistency. I want to make sure I understand the rationale for introducing a new namespace. @MartijnR?

Relatedly, should there be a namespace recommendation for organizations that want to add new functionality before consensus is reached here? Should that functionality be in `jr`/`orx` or perhaps in a namespace that identifies their org? I think it's clear it should not be in the http://www.w3.org/2002/xforms default namespace. If they used an org-specific namespace, I presume that would mean that their org namespace would become part of this spec if ever their functions were adopted. That's a positive because it identifies the origin of the functionality but it could mean there are a lot of namespaces to deal with.

**Comment by MartijnR** [comment]
The openrosa.org/xforms namespace is already supported, so it's not new. In my opinion, this neutral (not-implementation-related) namespace is the one to use.

If clients implement this spec and want to add their own custom functionality, they could:

1. Try to get it included in the spec by discussing here or in the dev forum. If successful, they could use the OpenRosa namespace right away. As an advantage they'll have received valuable technical input which may have improved their plan.
2. Go off on their own and use their own namespace (like openclinica.com/xforms, enketo.org/xforms etc, javarosa.org/xforms).

If a group chooses 2, and some time in the future, the (unchanged) feature gets adopted into the spec after all, for any reason, it would make sense to me to adopt the namespace they had chosen. This is how we could say the javarosa.org/xforms namespaced attributes got in in the past.

The difficulty is that it would seem to me far [better for the ecosystem](https://enketo.org/about/#enketo-ecosystem), that all actors at least actively try to use option 1 first. Option 2 will reduce interoperability more and more, eventually leading to the dissolution of the ecosystem. Quite a challenge. How to encourage this?

**Comment by lognaturel** [comment]
I'm sold on using openrosa.org/xforms namespace for custom features agreed on by the community here moving forward. The question was about whether it might be confusing or an over-optimization but now that I think more about it, very few orgs that do data collection look at the XML so it's only something that those building form engines and/or software form designers will need to think about. I like what you say about thinking of custom functionality in the javarosa.org/xforms namespace as originating from the JR implementation and differentiating those additions from what we all agree on moving forward. Unfortunately, JR is now itself fragmented with ODK, Dimagi, SurveyCTO, etc maintaining their own versions so I don't think anyone should be adding anything to the javarosa.org/xforms namespace at this point.

I agree with you that in an ideal world, all core functionality would be discussed and adopted at this spec level before it gets added to different implementations. But like you said, it has to not only be explicitly encouraged but also make sense for the orgs involved. Discussion generally takes longer than no discussion so moving ahead with a 'good enough' approach decided on in-house has many advantages. While I strongly agree that option 1 is best for the ecosystem, we should also recognize that option 2 may be necessary, especially for orgs tied to sales cycles and other outside pressures. I agree with each org picking a namespace for functionality that needs to be included before consensus is reached and the namespace being used in this spec if their proposal is eventually adopted.

Maybe we should explicitly state the benefits of having a unified spec. There are three big ones for me but would be interested in knowing if I'm missing something:
1. ODK users can mix and match tools and reassess which they use based on their changing needs. In particular, they don't get locked in to tools that may become deprecated.
1. ODK tool implementors can benefit from feedback from a broad range of collaborators when designing new core functionality (what you said).
1. ODK tool implementors can share core implementations (e.g. JavaRosa).

I think 1 is always true and is particularly valuable because at the end of the day, we're all trying to improve data collection outcomes in the long term. But reality means it's going to be hard to convince anyone to contribute here if 2 and 3 aren't true. And I believe they can only be true if there are technically strong contributors to the spec and core projects and consistent, timely progress made on both.

Here are some of the questions that I think need to be answered:
- How are decisions made on spec changes?
- How can a timely response to all proposals be ensured?
- How are spec changes communicated out to maintainers of ODK-compliant cores?
- How can timely updates to the shared core implementations (e.g JavaRosa) be ensured?

**Comment by lognaturel** [comment]
It would be great to get some feedback from orgs that maintain ODK-compliant or -derived form parsers and/or form builders. I don't know if this is a good idea but I'm going to try it -- Carter Center/Elmo (@hooverlunch), Dimagi (@ctsims), ESRI/Survey123 (@spatialdude), Kobo (@dorey), Ona (@ukanga @mberg), SurveyCTO (@chrislrobert) it would be wonderful to learn how you think about expansion of the ODK XForms spec. What would it take for you to propose these changes here before making them? How would you feel about namespacing additions you need to make before consensus is reached?

As a bit of context, @MartijnR maintains the Enketo core and I've been stirring up trouble as I work with @yanokwa and others to ensure a smooth transition of ODK out of UW.

**Comment by smoyte** [comment]
@lognaturel Thanks for reaching out. I don't believe we've ever added anything to the xforms XML used by ODK. We use stock ODK and build ELMO to speak stock ODKese. So I think I'm fine with whatever y'all come up with!

Unless I'm misunderstanding the question??

BTW, ELMO is maintained by [Sassafras Tech Collective](http://sassafras.coop) (my co-op) for The Carter Center (our client).

Thanks again!

**Comment by chrislrobert** [comment]
Thanks to you both for the wonderful discussion thus far, and for reaching
out. In principle, I like the idea of separate namespaces, and the user
impact is low, as you say, because few people code XML directly (honestly,
does anyone?). However, I am having a hard time thinking about how often
this would be relevant since it seems like many of our revisions are
modifications or extensions to existing functionality.

Also, would a new namespace have user-facing implications in terms of
function names? jr:choice-name() is, frankly, a travesty of a name when it
comes to UX, for example. Would we throw some "cryptic prefix with a colon"
onto all new functions? If so, then I think we need to find a way to
isolate XLSForm users from the ugliness. (The processor looks for an
implementation across namespaces?)

As for consulting the community, our trouble is that we already have a
dizzying number of stakeholders, internal and external, involved in the UI
and UX design process, involved in helping us to weigh engineering
trade-offs and run our R&D. Adding community members often creates a "too
many cooks in the kitchen" situation, particularly since each member of the
broader ODK community has their own interests and perspectives. I agree
that consultation is better for the ecosystem, other things equal -- but I
honestly don't know how to make it work in practice for fast-moving,
market-driven, rapidly-growing, resource-constrained companies like mine.
I'm open to trying to figure it out, but I think it's a tough problem.

**Comment by MartijnR** [comment]
@lognaturel I think the 3 "benefits" hit the nail on the head. Let's promote them! :)

> 1. ODK users can mix and match tools and reassess which they use based on their changing needs. In particular, they don't get locked in to tools that may become deprecated.

Definitely the key one. I'd add _"...deprecated or for which an attractive replacement becomes available"_. On its own point 1 is not necessarily compelling to somebody developing a data entry client, but at least to some it is (e.g Enketo).

> How are decisions made on spec changes?

Though, a formal structure would be fine with me, I'm very skeptical about this every working here. A more organic way of gaining voting power through actual collaboration on XForms Specification discussions might be more feasible. No participation means no objection?

> How can a timely response to all proposals be ensured?

I don't think we can ensure it. If we ourselves see a healthy expanding ecosystem of interoperable tools as our mission, we'd hopefully automatically commit to spending some time on the spec(s). So that would go back to your 3 points.

> How are spec changes communicated out to maintainers of ODK-compliant cores?

A changelog in the spec would seem sufficient to me. Forcing traffic to the specification may mean the outstanding issues/proposals get discussed.

> How can timely updates to the shared core implementations (e.g JavaRosa) be ensured?

This would be great, but I don't think we can do anything. Agreeing on a spec addition/change is agreeing on a feature being worthwhile and **how** this feature should be added. It's totally up to the orgs that maintain the tools and their constraints/priorities **when** to actually implement this, just like e.g. Safari is (annoyingly) almost always several years behind implementing new HTML-related specs.

> Also, would a new namespace have user-facing implications in terms of
function names?

@chrislrobert That's a very good point. I would not really want to namespace functions either. Can we justify not doing this?

**Comment by dorey** [comment]
I think this depends on what kind of additional functionality we are talking about. New question types? Changes to the flow of the survey? New functions in xpaths?

Caveat: I don't work with XForm XML directly, so most of my experience is through XLSForms and pyxform which all use the same namespaces and a mapping of `model>bind`s for individual question type. Originally, the mapping was configurable through a customizable [`question_types.xls`](https://github.com/XLSForm/pyxform/blob/75302249f25850f9a49e6ba9112abb6502e06693/pyxform/question_types/base.xls). However, over time, custom types were so few and far-between that the presets were hard coded into [a single data structure](https://github.com/XLSForm/pyxform/blame/cfe8589f40319fa3279b0a83e0d23d49bcbe8408/pyxform/question_type_dictionary.py#L29-L847).

I have come to appreciate the graceful fallback behavior of new or experimental question types in ODK-flavored-JavaRosa-XForms. This is most evident in Kobo when a submission from one tool (ODK Collect) needs to be opened and edited in another, like Enketo. Unsupported `bind`s show up as a basic text inputs. Nothing breaks.

Taking it a step further to a potential user-facing feature, the namespaces perhaps could be used to construct a link to a relevant help page, such as:
> `https://enketo.org/unsupported?namespace=openrosa.org/xforms&type=barcode`
> (⇧ hypothetical support URL could notify users of plans to support a particular question type; prompt users to inquire about funding the development of a feature; upgrading installation; etc)

Conclusion: Other than this hypothetical example, from my perspective there is no clear benefit to how we use namespaces.

_As for the discussions about how we should support expansion of the spec:_ I'll try to touch on this in a response to `#74`

**Comment by lognaturel** [comment]
I'll take a stab at #64 soon and highlight the benefits to maintaining a common ODK XForms spec as we've discussed here. Next time that we add something to this spec, we should make sure that the changelog is easy to find and share its location community-wide. Should the spec itself be versioned?

It sounds like we agree that XLSForms users should not have to worry about namespaces as they currently don't. Perhaps there is no real benefit to namespacing new functionality after all?

**Comment by dorey** [comment]
Are you referring to namespaces at the top of the document? Or the `jr:` parts of the attributes in the binds? (or are the two connected, and I'm only now realizing it?)

Inside an XLSForm, I could definitely see a benefit to keeping track of which "vocabularies" are in use in the survey: Which types are accepted, aliases are replaced, new/experimental features are available, etc. I'm not sure if this would necessarily correspond to XML namespaces though.

**Comment by MartijnR** [comment]
> or are the two connected, and I'm only now realizing it?

Yes ;). In pyxform, I don't think using XML namespaces is any issue. It's only used in the XForm output.

> Perhaps there is no real benefit to namespacing new functionality after all?

There is. It is to avoid collisions between custom extensions by different parties and with the W3C spec(s) (ie. W3C-spec-compliant libraries that may be used in data collection clients). There is no real benefit to **not** using them though [edit] **for XML attributes and XML nodes** [/edit].

Remaining question is whether it's acceptable to not use namespaces for custom XPath functions though. Those would require some more manipulation on the pyxform side to hide from users.

**Comment by lognaturel** [comment]
@MartijnR Thanks for that clarification, makes sense. I don't have a valid opinion on the XPath functions question. My gut says no namespace is the pragmatic choice but I may not be understanding the full implications.

@chrislrobert, moving forward, are you on board for namespacing any attributes and nodes you decide to add before community consensus is reached?

And as an aside, it looks like `jr:choice-name(string value, node node)` and `jr:itext(string arg)` are existing namespaced XPath functions and that they're simply not exposed in XLSForms. 

**[edit]**
I'm still learning so please help me overcome any misconceptions I display! I think the whole point of not namespacing XPath functions is that they're directly usable in XLSForm with no transformation, is that correct? So in fact `jr:choice-name` and  `jr:itext` are usable from XLSForm and require the `jr:` prefix. @MartijnR did I get that right this time?
**[/edit]**

**Comment by chrislrobert** [comment]
Sure, I have no objection to namespacing attributes and nodes -- though
we'll be caught in a backward-compatibility bind with respect to older ones
we already added... so I don't quite know how to go back and fix those
without tremendous disruption for Collect users in the field.

Shall we agree on namespace naming conventions?

**Comment by lognaturel** [comment]
Regarding compatibility, if I understand all this correctly, this might not affect so many users since XLSForms is generally what they interact with. Your existing non-namespaced additions are currently not ODK-compatible so your users are limited to your forks when using them in their forms. If those changes were submitted to and accepted by the broader community as-is, then I believe that would mean your users' Excel-based forms would suddenly become ODK-compatible since corresponding functionality in XLSForms is not namespaced. 

On the XForms side, if the additions were accepted without any namespace (as you have them now), then your core would also be ODK-compatible. If they were included in the spec but in the `openrosa.org/xforms` namespace, then your users' XML forms would not be ODK-compatible. Your core fork could still use the non-namespaced versions in addition to the ones in the `openrosa.org/xforms` namespace and your users would be no worse off than now.

@MartijnR @chrislrobert does that sound right or did I miss something?

As for the namespace names, I'd say `http://<org domain>/xforms` makes sense. So that would be `http://surveycto.com/xforms`, `http://enketo.org/xforms`, etc. The prefix (`jr`, `orx`) is just for convenience so you can pick what makes sense to you internally.

**Comment by MartijnR** [comment]
Yes, this all makes perfect sense. Choosing an organization's actual custom namespace URI is really up to the organization, but the convention proposed is nice. In my opinion it's even nicer if the URI is also a public webpage that  describes the customizations but that's not an XML requirement at all if I remember correctly. [More here](https://en.wikipedia.org/wiki/XML_namespace).

Hopefully, being compliant with our spec will become so desirable, that we'll get lots of solid proposals and orgs won't have much of a need for custom extensions for new features. :) 🥇

**Comment by chrislrobert** [comment]
http://surveycto.com/xforms for our namespace sounds reasonable to me..!

**Comment by lognaturel** [comment]
I think we've reached agreement? I'm happy to take a stab at #77 (summarizing all this in a way that's useful for the spec audience) if it's helpful.

**Comment by MartijnR** [comment]
I think so too, and yes please!

**Comment by yanokwa** [comment]
I hate to bring this thread back to life, but I just thought of it. Instead of OpenRosa (`orx`) which is an organization that doesn't even kind of exist, why not `odk` as the primary namespace? I mean the spec lives in ODK. The primary library lives in ODK. Everyone thinks of the ecosystem as the ODK ecosystem. And we own the domain already.

**Comment by chrislrobert** [comment]
Makes a lot of sense! But what would be the ramifications? We'd just shift
moving forward, but be backward-compatible?

**Comment by MartijnR** [comment]
I have no more resistance to using an odk (http://opendatakit.org/xforms ?) namespace for new features that have no known implementations elsewhere e.g. commcare, enketo. (so for odk:setlocation, odk:rank).
