### ISSUE TITLE
start a changelog

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#76]
Maybe without versioning is fine, e.g. like this where each date covers all merged PRs on that date?

[2017-01-05]
--------------------
#### Added:
- a new feature

#### Removed:
- a deprecated feature

#### Fixed:
- a correction of an error

#### Changed:
- an edit to a (sub)section to clarify or correct spelling/grammar, or we could leave this out entirely to make it easier to parse the changelog.

**Comment by lognaturel** [comment]
Yes, that sounds great! Where are you thinking of putting it?

What happens with forms that have deprecated features? Is it up to each engine to decide how to handle them? How would a user match the state of their form to the changelog? With a version number, it seems like the form update story is better. That said, maybe that's more important at the XLSForm level. Or if there aren't many breaking changes, then I suppose it's not terribly relevant.

**Comment by lognaturel** [comment]
Just to be super clear, what I'm concerned about is knowing for any given form what tool versions I can use it with. If the form doesn't have any indication of what version of the spec it adheres to, that question seems really hard to answer. If we're speeding up improvements on this front in addition to the XLSForm front, we will most certainly end up with ecosystem pieces that lag behind and conversely, we'll still have older forms around.

**Comment by MartijnR** [comment]
I was thinking, a CHANGELOG.md file in the root of this repo with a link somewhere in the introduction of the spec.

I understand your concern and versioning solution, but I'm wondering if we'd be making things too complex if we publish the specification version in each form. In reality, I think the chance that we encounter such serious problems due to changes in the spec, is too low to necessitate starting to version now. 

Most feature-issues are probably engine-related and not spec-related, and are better dealt with by client-detection. E.g. Enketo doesn't support local encryption, but detects forms that require this and shows a warning. Versioning wouldn't really help with this, because local encryption has been in the spec since version 0.

Another real-life issue is fixing a bug in the implementation of the spec which is not detectable in the form and probably does really require some kind of engine-versioning (as Mitch proposed [here](https://groups.google.com/forum/#!searchin/opendatakit-developers/current%7Csort:relevance/opendatakit-developers/nN8HTA5pUIM/QVO7fnTqAQAJ)). We could end up with two versions (engine + spec).

How about we just postpone this decision until we change the spec in such a way that it becomes necessary to clearly separate it from the previous "version"? When that happens we could e.g. alter the OpenRosa XForms namespace path part by appending a version.

**Comment by lognaturel** [comment]
Sounds good to postpone the decision until we can better understand exactly what the needs are. Really, a comment with the date the form was authored on would probably make most issues traceable.

Having a markdown changelog linked from the top of the spec sounds great. Let's do it!
