### ISSUE TITLE
Document mediatype attribute for upload element

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#78]
Is there a reason this is not explicitly called out?

**Comment by MartijnR** [comment]
duplicate: https://github.com/opendatakit/xforms-spec/issues/24

**Comment by lognaturel** [comment]
Maybe, though I think this is easier! I just want some evidence somewhere of the existence of `mediatype`. I agree that documenting possible media types is harder and maybe best left to the implementations (maybe this spec can explicitly say that). I'd decouple the two but they can be joined if you prefer.

**Comment by MartijnR** [comment]
Ah yes, that makes sense. Sorry I misunderstood.
