### ISSUE TITLE
How/when should the changelog be updated?

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#92]
Maybe the person who does the merge can edit it directly without doing a PR? Should it really be updated for every little change or should we batch them somehow?

**Comment by MartijnR** [comment]
Yes, part of the PR I think.

I don't think we should update for everything. Maybe only:

* added: actual additions to the spec (e.g. the accept attribute, the XML external data)
* removed: any deprecated stuff we no longer want to document
* fixed (or changed): any serious documentation errors that were corrected

**Comment by lognaturel** [comment]
(Missing some words in that there title! Oooops!)

The challenge with having it be part of the PR is that it could be reviewed and agreed on a lot later, no?

**Comment by MartijnR** [comment]
Ah yes, that's true. How about we just add it after a PR is approved, without actually creating a PR for the changelog change?

**Comment by lognaturel** [comment]
Sounds good. I think whoever does the review and merge should do it since the contributor may not have commit privileges.

**Comment by MartijnR** [comment]
deal!
