### ISSUE TITLE
Add a "double entry" convenience modifier

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#93]
This is a half-baked idea inspired by @wonderchook

Double entry can significantly increase data quality. It would be nice to have a way for form designers to specify that fields should be double-entered. The enumerator would then see a duplicate widget and maybe get a warning when the values don't match.

I imagine this being useful for string, number and select values.

This could possibly be at the XLSForm level.

**Comment by MartijnR** [comment]
That's cool indeed. At first glance, think it's best to do this on the XLSForm side, creating a duplicate question with (possibly) different logic and maybe a new "duplicate-check" appearance (if wanting to display this question differently). I think doing the magical part on the XLSForm side will allow more flexibility on the XForms side to tweak this functionality by e.g. showing different (translated) constraint messages, different relevant etc.

**Comment by lognaturel** [comment]
I agree this shouldn't be in this spec.
